### ISSUE TITLE
[BUG] Bug when calling intialize() for Zilswap

### ISSUE THREAD

**Issue by HoJinKind** [Switcheo/zilswap-sdk#20]
**Describe the bug**

**To Reproduce**
1. Switch to use MainNet
2.  run intialize()
3. See error FetchError: invalid json response body at https://api.zilliqa.com/ reason: Unexpected token < in JSON at position 0

**Expected behavior**
Expected it to work

**Screenshots**
<img width="941" alt="Screenshot 2021-07-07 at 11 14 06 PM" src="https://user-images.githubusercontent.com/34650280/124784996-0dc54100-df79-11eb-9743-d717e2a6d32b.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HoJinKind** [comment]
hmm managed to get it to work with MainNet to 'https://ssn.zillacracy.com/api'

**Comment by aref-mehran** [comment]
> hmm managed to get it to work with MainNet to 'https://ssn.zillacracy.com/api'

hi https://ssn.zillacracy.com/api doenst work have you found any soloution?
